# Generated by Django 5.2.1 on 2025-06-06 19:13

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtask",
            name="title",
            field=models.CharField(
                max_length=100,
                unique_for_date="created_at",
                verbose_name="Subtask Title",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(
                max_length=100, unique_for_date="created_at", verbose_name="Task Title"
            ),
        ),
        migrations.AddIndex(
            model_name="subtask",
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=["created_at"], name="subtask_created_at_brin"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=["created_at"], name="task_created_at_brin"
            ),
        ),
    ]
