# Generated by Django 5.2.1 on 2025-07-15 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0002_alter_subtask_title_alter_task_title_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="subtask",
            options={"ordering": ["-created_at"], "verbose_name": "SubTask"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-created_at"], "verbose_name": "Task"},
        ),
        migrations.AlterModelTable(
            name="category",
            table="task_manager_category",
        ),
        migrations.AlterModelTable(
            name="subtask",
            table="task_manager_subtask",
        ),
        migrations.AlterModelTable(
            name="task",
            table="task_manager_task",
        ),
    ]
