# Generated by Django 5.2.1 on 2025-07-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0003_alter_category_options_alter_subtask_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="deleted_at",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Is Deleted"),
        ),
    ]
