# Generated by Django 5.2.1 on 2025-07-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0004_category_deleted_at_category_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Task Title"),
        ),
    ]
