# Generated by Django 5.2.1 on 2025-07-31 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0007_subtask_owner_task_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "permissions": [("can_get_statistic", "Can get genres statistic")],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
